# Generated by Django 5.1.2 on 2024-11-02 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_todo', '0004_rem_task_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new_task',
            name='date_complete',
            field=models.DateTimeField(blank=True, default=None),
        ),
    ]
