# Generated by Django 5.1.2 on 2024-11-02 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_todo', '0005_alter_new_task_date_complete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new_task',
            name='date_complete',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
